baseURL: https://samples.christianf.io/
title: Sample Documentation
languageCode: en-us

enableGitInfo: true

contentDir: content
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

module:
  proxy: direct
  hugoVersion:
    extended: true
    min: 0.73.0
  imports:
    - path: github.com/google/docsy
      disable: false

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    style: tango

menu:
  main:
    - name: GitHub
      url: https://github.com/nandstand/sample-site
      weight: 20
    - name: Personal Site
      url: https://christianf.io/
      weight: 30

params:
  gcs_engine_id: d72aa9b2712488cc3
  sidebar_search_disable: false
  copyright:
    authors: Christian Fuller
  ui:
    breadcrumb_disable: false
    navbar_logo: false
    sidebar_menu_compact: false
    sidebar_menu_foldable: false
