baseURL: https://nandstand.github.io/sample-site/
languageCode: en-us
title: Sample Documentation
theme: docsy
frontmatter:
  format: yaml
enableEmoji: true
enableGitInfo: true
module:
  proxy: direct
  hugoVersion:
    extended: true
    min: 0.73.0
  imports:
    - path: github.com/google/docsy
      disable: false
